# Examine version 3 of the catalog with amplitudes 

This notebook is used to check whether the amplitude information is correctly added to version 3 of the pick assignment table. 

By Hiroto Bito

In [1]:
import os
import pandas as pd

In [4]:
datasets_dir =  '/wd1/hbito_data/data/datasets_all_regions'
path_assigned_picks_df = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3_w_amp.csv'
assigned_picks_df = pd.read_csv(path_assigned_picks_df, index_col=False)
assigned_picks_df.head(10)

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,437.748450
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0,30.590310
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,437.748450
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0,3479.641453
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3,10.394249
5,5,2010-01-01T00:15:43.768400Z,PB.B943,S,-0.511,0,5,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813202,-122.911301,84.2,8.335411
6,6,2010-01-01T00:15:48.060400Z,UW.BOW,S,-0.263,0,6,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.474831,-123.229301,870.0,13.128843
7,7,2010-01-01T00:17:04.730000Z,UW.PASS,P,-0.499,1,7,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,48.998299,-122.085197,175.4,185.009417
8,8,2010-01-01T00:17:05.008400Z,PB.B943,P,-0.252,1,8,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,47.813202,-122.911301,84.2,6.398308
9,9,2010-01-01T00:17:05.020400Z,UW.BLN,P,0.415,1,9,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,48.006624,-122.972646,601.0,21.684127

In [7]:
skipped_csv_path = f'{datasets_dir}/calculate_amplitudes_skipped_picks_test.csv'
skipped_picks_df = pd.read_csv(skipped_csv_path)
skipped_picks_df

,network,station,channel,origin_time,time_pick,starttime,endtime,reason
0,UW,VVHS,*H*,2010-04-16T22:48:21.535000Z,2010-04-16T22:48:24.980000Z,2010-04-16T22:48:24.480000Z,2010-04-16T22:48:26.980000Z,Request failed: No Vertical Component Data Pre...
1,CN,HNB,*H*,2010-04-28T14:36:42.921000Z,2010-04-28T14:36:53.940000Z,2010-04-28T14:36:53.440000Z,2010-04-28T14:36:55.940000Z,Request failed: No Vertical Component Data Pre...
2,UW,SP2,*H*,2010-04-30T16:01:16.639000Z,2010-04-30T16:01:35.360000Z,2010-04-30T16:01:34.860000Z,2010-04-30T16:01:37.360000Z,Request failed: No Vertical Component Data Pre...
3,UW,SP2,*H*,2010-04-30T20:11:55.912000Z,2010-04-30T20:12:05.360000Z,2010-04-30T20:12:04.860000Z,2010-04-30T20:12:07.360000Z,Request failed: No Vertical Component Data Pre...
4,UW,SP2,*H*,2010-05-01T04:18:47.446000Z,2010-05-01T04:18:57.850000Z,2010-05-01T04:18:57.350000Z,2010-05-01T04:18:59.850000Z,Request failed: No Vertical Component Data Pre...
...,...,...,...,...,...,...,...,...
30853,BK,JCC,*H*,2014-09-25T10:46:35.607000Z,2014-09-25T10:46:46.728393Z,2014-09-25T10:46:46.228393Z,2014-09-25T10:46:48.728393Z,Request failed: No Vertical Component Data Pre...
30854,BK,JCC,*H*,2014-09-25T12:28:45.893000Z,2014-09-25T12:28:51.818393Z,2014-09-25T12:28:51.318393Z,2014-09-25T12:28:53.818393Z,Request failed: No Vertical Component Data Pre...
30855,BK,JCC,*H*,2014-09-25T12:28:45.893000Z,2014-09-25T12:28:57.368393Z,2014-09-25T12:28:56.868393Z,2014-09-25T12:28:59.368393Z,Request failed: No Vertical Component Data Pre...
30856,NC,KCR,*H*,2014-09-26T01:51:31.969000Z,2014-09-26T01:51:37.047700Z,2014-09-26T01:51:36.547700Z,2014-09-26T01:51:39.047700Z,Request failed: No Vertical Component Data Pre...
30857,NC,KCR,*H*,2014-09-26T01:51:31.969000Z,2014-09-26T01:51:41.167700Z,2014-09-26T01:51:40.667700Z,2014-09-26T01:51:43.167700Z,Request failed: No Vertical Component Data Pre...

test

In [ ]:
path_test = f'{datasets_dir}Cascadia_updated_catalog_picks_assignment_ver_3.csv'
test_df = pd.read_csv(path_test, index_col=False)
print(len(test_df))

1004335

end test

In [3]:
# Read the data frame
datasets_dir =  '/wd1/hbito_data/data/datasets_all_regions'

# Prepare output CSV path (copy)
output_csv_path = f'{datasets_dir}/Cascadia_updated_catalog_picks_assignment_ver_3_w_amp.csv'

# Read the files
if os.path.exists(output_csv_path):
    assigned_picks_df = pd.read_csv(output_csv_path, index_col=False)
else:
    assigned_picks_df = pd.read_csv(path_assigned_picks_df, index_col=False)

assigned_picks_df

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,192.775133
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0,22.919488
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0,192.775133
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0,2563.868268
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.1470,0.680,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3,7.217193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,59995,2010-06-26T20:42:06.091500Z,UW.BHW,P,-0.283,4328,59995,47.95708,-121.93785,14.7345,0.665,2010-06-26 20:42:01.257000+00:00,0.461,2,4,6,47.836360,-122.030570,152.0,NaN
59996,59996,2010-06-26T20:42:16.471500Z,UW.HDW,P,-0.556,4328,59996,47.95708,-121.93785,14.7345,0.665,2010-06-26 20:42:01.257000+00:00,0.461,2,4,6,47.649030,-123.053500,987.4,NaN
59997,59997,2010-06-26T20:42:23.758400Z,PB.B943,S,0.200,4328,59997,47.95708,-121.93785,14.7345,0.665,2010-06-26 20:42:01.257000+00:00,0.461,2,4,6,47.813202,-122.911301,84.2,NaN
59998,59998,2010-06-26T20:42:23.768400Z,PB.B013,S,0.220,4328,59998,47.95708,-121.93785,14.7345,0.665,2010-06-26 20:42:01.257000+00:00,0.461,2,4,6,47.813000,-122.910797,75.3,NaN
59999,59999,2010-06-26T20:42:24.821500Z,UW.BLN,S,0.869,4328,59999,47.95708,-121.93785,14.7345,0.665,2010-06-26 20:42:01.257000+00:00,0.461,2,4,6,48.006624,-122.972646,601.0,NaN

In [9]:
assigned_picks_df.iloc[4000:4020]

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
4000,4000,2010-01-10T05:55:36.838400Z,PB.B932,S,-0.439,271,4000,40.63636,-124.61929,14.4650,0.785,2010-01-10 05:55:19.999000+00:00,0.338,5,4,9,40.275002,-124.221199,52.0,NaN
4001,4001,2010-01-10T05:55:45.038400Z,PB.B933,S,-0.238,271,4001,40.63636,-124.61929,14.4650,0.785,2010-01-10 05:55:19.999000+00:00,0.338,5,4,9,40.060001,-123.969002,268.1,NaN
4002,4002,2010-01-10T05:55:45.738400Z,PB.B049,S,0.288,271,4002,40.63636,-124.61929,14.4650,0.785,2010-01-10 05:55:19.999000+00:00,0.338,5,4,9,40.237499,-123.819702,117.0,NaN
4003,4003,2010-01-10T06:00:53.068400Z,PB.B046,P,-0.594,272,4003,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.321972,-124.284302,44.0,NaN
4004,4004,2010-01-10T06:00:53.858400Z,PB.B932,P,-0.097,272,4004,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.275002,-124.221199,52.0,NaN
4005,4005,2010-01-10T06:00:56.068400Z,PB.B933,P,-0.077,272,4005,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.060001,-123.969002,268.1,NaN
4006,4006,2010-01-10T06:00:57.588400Z,PB.B049,P,1.190,272,4006,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.237499,-123.819702,117.0,NaN
4007,4007,2010-01-10T06:00:58.718400Z,PB.B935,P,0.293,272,4007,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.478699,-123.573196,696.7,NaN
4008,4008,2010-01-10T06:00:59.708400Z,PB.B046,S,0.128,272,4008,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.321972,-124.284302,44.0,NaN
4009,4009,2010-01-10T06:01:01.068400Z,PB.B932,S,0.913,272,4009,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.275002,-124.221199,52.0,NaN
4010,4010,2010-01-10T06:01:03.898400Z,PB.B049,S,-0.548,272,4010,40.36486,-124.50471,40.2395,0.719,2010-01-10 06:00:46.317000+00:00,0.615,5,3,8,40.237499,-123.819702,117.0,NaN
4011,4011,2010-01-10T06:04:27.098400Z,PB.B046,P,-0.123,273,4011,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,40.321972,-124.284302,44.0,NaN
4012,4012,2010-01-10T06:04:27.858400Z,PB.B932,P,-0.126,273,4012,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,40.275002,-124.221199,52.0,NaN
4013,4013,2010-01-10T06:04:31.218400Z,PB.B049,P,0.416,273,4013,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,40.237499,-123.819702,117.0,NaN
4014,4014,2010-01-10T06:04:32.018400Z,PB.B933,P,0.428,273,4014,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,40.060001,-123.969002,268.1,NaN
4015,4015,2010-01-10T06:04:32.028400Z,PB.B935,P,0.572,273,4015,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,40.478699,-123.573196,696.7,NaN
4016,4016,2010-01-10T06:04:49.218400Z,PB.B036,P,0.038,273,4016,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,42.505833,-123.381668,315.3,NaN
4017,4017,2010-01-10T06:04:49.268400Z,PB.B035,P,0.130,273,4017,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,42.503513,-123.383415,370.0,NaN
4018,4018,2010-01-10T06:04:59.330600Z,UW.HSO,P,-4.113,273,4018,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,43.525661,-123.091797,1016.0,NaN
4019,4019,2010-01-10T06:05:00.620000Z,UW.UMPQ,P,1.117,273,4019,40.70559,-124.45052,21.0060,0.754,2010-01-10 06:04:18.810000+00:00,1.071,11,10,21,43.290890,-123.331880,164.4,NaN