# Calculate the amplitudes

This notebook is used to calculate the amplitudes of the seismograms.

Agentic AI was used in this notebook.

By Hiroto Bito

In [25]:
import sys
import pandas as pd
import numpy as np
import time

from obspy import read, UTCDateTime
from obspy.clients.fdsn import Client
from obspy.core.stream import Stream

parent_dir = '/home/hbito/cascadia_obs_ensemble/utils'
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from data_client import get_waveforms

In [26]:
path_assigned_picks_df = '/wd1/hbito_data/data/datasets_all_regions/Cascadia_updated_catalog_picks_assignment_ver_3.csv'
assigned_picks_df = pd.read_csv(path_assigned_picks_df, index_col=False)
assigned_picks_df.head(10)

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation
0,0,2010-01-01T00:15:27.180000Z,UW.PCMD,P,0.049,0,0,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
1,1,2010-01-01T00:15:37.840400Z,UW.RVW,P,1.264,0,1,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.149750,-122.742996,504.0
2,2,2010-01-01T00:15:33.280000Z,UW.PCMD,S,-0.243,0,2,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.888962,-122.301483,239.0
3,3,2010-01-01T00:15:42.002000Z,UW.GNW,S,2.402,0,3,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.564130,-122.824980,220.0
4,4,2010-01-01T00:15:43.618400Z,PB.B013,S,-0.651,0,4,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813000,-122.910797,75.3
5,5,2010-01-01T00:15:43.768400Z,PB.B943,S,-0.511,0,5,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,47.813202,-122.911301,84.2
6,6,2010-01-01T00:15:48.060400Z,UW.BOW,S,-0.263,0,6,47.13396,-122.09098,60.147,0.68,2010-01-01 00:15:16.204000+00:00,1.081,2,5,7,46.474831,-123.229301,870.0
7,7,2010-01-01T00:17:04.730000Z,UW.PASS,P,-0.499,1,7,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,48.998299,-122.085197,175.4
8,8,2010-01-01T00:17:05.008400Z,PB.B943,P,-0.252,1,8,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,47.813202,-122.911301,84.2
9,9,2010-01-01T00:17:05.020400Z,UW.BLN,P,0.415,1,9,48.17742,-121.83289,6.163,0.84,2010-01-01 00:16:49.343000+00:00,0.985,25,30,55,48.006624,-122.972646,601.0

test

In [6]:
len(assigned_picks_df['idx'].unique())

63887

In [12]:
test = assigned_picks_df['idx'].unique()[:10]

In [13]:
for i in range(len(test)):
    print(test[i])

0
1
2
3
4
5
6
7
8
9

end test

Pseudo code

orid = assigned_picks_df['idx'].unique()[:10]


for i in range(len(orid)):
    idx = orid[i]

    df_origin = assigned_picks_df[]

End pseudo code

In [27]:
n_picks = 10

In [28]:
ls_idx = np.random.choice(a=len(assigned_picks_df), size=(n_picks))
ls_idx

array([381518, 407388, 635511, 382460, 257444, 614800, 183073, 835184,
       657537, 311738])

In [36]:
# Take the subset (customize your filter as needed)
subset = assigned_picks_df.iloc[ls_idx].copy()
subset

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation
381518,381518,2012-09-13T04:06:56.048400Z,PB.B203,S,-0.049,25760,381518,46.50697,-122.42590,17.9390,0.938,2012-09-13 04:06:43.898000+00:00,0.830,15,23,38,46.168999,-122.333664,814.4
407388,407388,2012-10-07T04:59:06.741600Z,7D.J25B,S,1.159,27104,407388,40.40453,-124.50117,13.7290,0.668,2012-10-07 04:57:15.988000+00:00,0.508,4,12,16,44.471298,-124.621696,-147.0
635511,635511,2014-01-26T12:15:55.020000Z,CN.VGZ,P,-0.857,41592,635511,47.82530,-121.91765,8.6965,0.639,2014-01-26 12:15:34.188000+00:00,2.015,8,12,20,48.413100,-123.325100,67.0
382460,382460,2012-09-14T07:54:53.630900Z,7D.FS09B,S,2.725,25816,382460,42.06004,-126.36523,8.5730,0.797,2012-09-14 07:53:59.557000+00:00,1.277,18,19,37,40.438702,-124.808502,-2161.0
257444,257444,2012-01-19T16:53:43.998400Z,PB.B202,P,0.104,18213,257444,46.97234,-121.89146,4.2805,0.931,2012-01-19 16:53:30.085000+00:00,0.751,34,33,67,46.244700,-122.136700,1218.6
614800,614800,2013-12-05T00:20:08.600000Z,CN.SHB,S,-0.951,40205,614800,49.83096,-124.57185,3.9425,0.766,2013-12-05 00:19:50.380000+00:00,1.387,6,5,11,49.598500,-123.877100,1129.0
183073,183073,2011-07-17T13:01:31.718400Z,PB.B933,S,-0.814,12966,183073,40.33475,-124.41553,12.8400,0.868,2011-07-17 13:01:16.218000+00:00,0.650,6,6,12,40.060001,-123.969002,268.1
835184,835184,2014-11-12T18:30:52.500000Z,CN.PGC,P,-0.158,53981,835184,48.61889,-123.88791,23.0875,0.640,2014-11-12 18:30:45.437000+00:00,0.842,5,7,12,48.649800,-123.452100,12.0
657537,657537,2014-03-10T07:25:55.077700Z,NC.KSXB,S,-0.797,42925,657537,40.58016,-125.40211,12.5770,0.853,2014-03-10 07:25:08.450000+00:00,0.531,9,11,20,41.830379,-123.876884,1136.0
311738,311738,2012-05-08T01:36:31.605000Z,UW.LRIV,S,0.604,21378,311738,47.73982,-124.08626,31.5295,0.862,2012-05-08 01:36:13.554000+00:00,0.815,34,35,69,48.057500,-123.504000,293.8

test

In [19]:
subset.keys()

Index(['Unnamed: 0', 'time_pick', 'station', 'phase', 'timeres', 'idx', 'arid',
       'latitude', 'longitude', 'depth', 'Detection Value', 'time',
       'RMS Residual (s)', 'Num. P', 'Num. S', 'picks', 'slatitude',
       'slongitude', 'selevation'],
      dtype='object')

In [15]:
for idx, row in subset.iterrows():
    print(row['station'])

7D.G10D
NC.KMPB
PB.B024
UW.OSD
PB.B013
UW.UMPQ
PB.B033
PB.B932
CN.NLLB
PB.B046

In [10]:
window_before = 0.5 # in sec
window_after = 2 # in sec
source = 'pnwstore'

In [20]:
 # Define the arguments 
idx_test = 150
row = assigned_picks_df.iloc[idx_test]
date, _time = row['time'].split(' ')
datetime_str = date+'T'+_time
origin_time = UTCDateTime(datetime_str)  # Accept ISO string directly

network = row['station'].split('.')[0].strip()
station = row['station'].split('.')[1].strip()
channel = '*H*'
starttime = origin_time - window_before 
endtime = origin_time + window_after

time_pick = row['time_pick']        

# Request a waveform
time.sleep(0.1)

try:
    st = get_waveforms(network=network, station=station, channel=channel,
                        starttime=starttime, endtime=endtime,
                        source=source)
except Exception as e:
    print(f"Request failed: {e}")
    st = Stream()

time.sleep(0.1)

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

In [21]:
st

6 Trace(s) in Stream:
PB.B011..EH1 | 2010-01-01T18:16:52.608400Z - 2010-01-01T18:16:55.108400Z | 100.0 Hz, 251 samples
PB.B011..EH2 | 2010-01-01T18:16:52.608400Z - 2010-01-01T18:16:55.108400Z | 100.0 Hz, 251 samples
PB.B011..EHZ | 2010-01-01T18:16:52.608400Z - 2010-01-01T18:16:55.108400Z | 100.0 Hz, 251 samples
PB.B011..LH1 | 2010-01-01T18:16:53.069500Z - 2010-01-01T18:16:55.069500Z | 1.0 Hz, 3 samples
PB.B011..LH2 | 2010-01-01T18:16:53.069500Z - 2010-01-01T18:16:55.069500Z | 1.0 Hz, 3 samples
PB.B011..LHZ | 2010-01-01T18:16:53.069500Z - 2010-01-01T18:16:55.069500Z | 1.0 Hz, 3 samples

In [22]:
len(st)

6

end test

In [37]:
window_before = 0.5 # in sec
window_after = 2 # in sec
freq_highpass = 2 # in Hz
new_sampling_rate = 100 # in Hz

In [38]:
amplitudes = []

for idx, row in subset.iterrows():

    # Define the arguments 
    date, _time = row['time'].split(' ')
    datetime_str = date+'T'+_time
    origin_time = UTCDateTime(datetime_str)  # Accept ISO string directly

    network = row['station'].split('.')[0].strip()
    station = row['station'].split('.')[1].strip()
    channel = '*H*'
    starttime = origin_time - window_before 
    endtime = origin_time + window_after

    time_pick = row['time_pick']        

    # Request a waveform
    time.sleep(0.1)

    try:
        st = get_waveforms(network=network, station=station, channel=channel,
                            starttime=starttime, endtime=endtime,
                            source=source)
    except Exception as e:
        print(f"Request failed: {e}")
        st = Stream()

    time.sleep(0.1)


    # Create a new stream
    sdata = Stream()
    
    # Check if loaded data have a vertical component (minimum requirement)
    has_Z = bool(st.select(id=f'{network}.{station}..??Z'))
    # Check for HH and BH channels presence
    has_HH = bool(st.select(id=f'{network}.{station}..HH?'))
    has_BH = bool(st.select(id=f'{network}.{station}..BH?'))
    has_EH = bool(st.select(id=f'{network}.{station}..EH?'))

    if not has_Z:
        print(f'No Vertical Component Data Present at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick}. Skipping')
        continue

    # Apply selection logic based on channel presence
    if has_HH:
        # If all HH, BH, and EH, channels are present, select only HH
        sdata += st.select(id=f'{network}.{station}..HH*')
    elif has_BH:
        # If BH and EH channels are present, select only BH
        sdata += st.select(id=f'{network}.{station}..BH*')
    elif has_EH:
        # If only EH channels are present, select only EH
        # NTS: This may result in getting only vertical component data - EH? is used for PNSN analog stations
        # NTS: This may also be tricky for pulling full day-volumes because the sampling rate shifts for
        #      analog stations due to the remote digitization scheme used with analog stations
        sdata += st.select(id=f'{network}.{station}..EH*')
    else:
        print(f'No data available at {network}.{station} with HHZ, BHZ or EHZ channels at {time_pick}. Skipping.')
        continue

    # Resample
    sdata.resample(new_sampling_rate)
        
    # Apply highpass filter
    sdata.detrend(type='demean')
    sdata.taper(max_percentage=0.5)
    sdata.filter(type='highpass', freq=freq_highpass)
    # tr.filter(type='bandpass', freqmin=freqmin, freqmax=freqmax)

    max_amp = 0
    for tr in sdata:
        max_amp = max(max_amp, abs(tr.data).max())

    amplitudes.append(max_amp)

# Append to DataFrame
subset.loc[:,"Amplitude"] = amplitudes

PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09
PNWstore | WARNING | Missing mount for year 2023 at /auto/pnwstore1-wd09

In [39]:
# Print the subset of the data frame with the new "Amplitude" column
subset

,Unnamed: 0,time_pick,station,phase,timeres,idx,arid,latitude,longitude,depth,Detection Value,time,RMS Residual (s),Num. P,Num. S,picks,slatitude,slongitude,selevation,Amplitude
381518,381518,2012-09-13T04:06:56.048400Z,PB.B203,S,-0.049,25760,381518,46.50697,-122.42590,17.9390,0.938,2012-09-13 04:06:43.898000+00:00,0.830,15,23,38,46.168999,-122.333664,814.4,6.324936
407388,407388,2012-10-07T04:59:06.741600Z,7D.J25B,S,1.159,27104,407388,40.40453,-124.50117,13.7290,0.668,2012-10-07 04:57:15.988000+00:00,0.508,4,12,16,44.471298,-124.621696,-147.0,91.125507
635511,635511,2014-01-26T12:15:55.020000Z,CN.VGZ,P,-0.857,41592,635511,47.82530,-121.91765,8.6965,0.639,2014-01-26 12:15:34.188000+00:00,2.015,8,12,20,48.413100,-123.325100,67.0,99.527351
382460,382460,2012-09-14T07:54:53.630900Z,7D.FS09B,S,2.725,25816,382460,42.06004,-126.36523,8.5730,0.797,2012-09-14 07:53:59.557000+00:00,1.277,18,19,37,40.438702,-124.808502,-2161.0,858.111612
257444,257444,2012-01-19T16:53:43.998400Z,PB.B202,P,0.104,18213,257444,46.97234,-121.89146,4.2805,0.931,2012-01-19 16:53:30.085000+00:00,0.751,34,33,67,46.244700,-122.136700,1218.6,6.493978
614800,614800,2013-12-05T00:20:08.600000Z,CN.SHB,S,-0.951,40205,614800,49.83096,-124.57185,3.9425,0.766,2013-12-05 00:19:50.380000+00:00,1.387,6,5,11,49.598500,-123.877100,1129.0,7.880846
183073,183073,2011-07-17T13:01:31.718400Z,PB.B933,S,-0.814,12966,183073,40.33475,-124.41553,12.8400,0.868,2011-07-17 13:01:16.218000+00:00,0.650,6,6,12,40.060001,-123.969002,268.1,4.484269
835184,835184,2014-11-12T18:30:52.500000Z,CN.PGC,P,-0.158,53981,835184,48.61889,-123.88791,23.0875,0.640,2014-11-12 18:30:45.437000+00:00,0.842,5,7,12,48.649800,-123.452100,12.0,345.709507
657537,657537,2014-03-10T07:25:55.077700Z,NC.KSXB,S,-0.797,42925,657537,40.58016,-125.40211,12.5770,0.853,2014-03-10 07:25:08.450000+00:00,0.531,9,11,20,41.830379,-123.876884,1136.0,36.324409
311738,311738,2012-05-08T01:36:31.605000Z,UW.LRIV,S,0.604,21378,311738,47.73982,-124.08626,31.5295,0.862,2012-05-08 01:36:13.554000+00:00,0.815,34,35,69,48.057500,-123.504000,293.8,23.394377