This notebooks is for examining the file that I received from Ian McBreatry on 10/7/2025. The file is about the updated locations after doing the cross correlation. 

Auth: Hiroto Bito <br>
Date: 10/14/2025

In [13]:
import pandas as pd

##### Import the file with the updated locations

In [14]:
# Read CSV file without header and assign column names
df_updated = pd.read_csv('/wd1/hbito_data/data/datasets_all_regions/updated_loctions_Cascadia.csv', 
                   header=None, 
                   names=['Latitude', 'Longitude', ' Depth (m)', 'sec_day'])
df_updated.head()

   Latitude  Longitude   Depth (m)    sec_day
0  47.13396 -122.09098    -60147.0    916.204
1  48.17742 -121.83289     -6163.0   1009.343
2  47.85353 -122.12435    -18296.0  26283.837
3  47.97665 -122.90617    -20910.0  31916.196
4  45.86019 -122.19002     -8403.5  58363.926

In [ ]:
len(df_updated) # len(df_updated) matches the original number of relocated events (63887)

63887

##### Import the most recent file of relocation

In [16]:
df_ver3 = pd.read_csv('/wd1/hbito_data/data/datasets_all_regions/Cascadia_relocated_catalog_ver_3.csv')

In [17]:
df_ver3

,Latitude,Longitude,Depth (km),Origin Time (UTC),Uncertainity (km),Horizontal Uncertainity (km),Geometric Std. (km),Detection Value,Num. P,Num. S,RMS Residual (s),Event ID
0,47.22533,-122.16895,56.111,2010-01-01T00:15:17.262282Z,10.223,10.216,0.790,0.680,2,5,1.081,0
1,48.19518,-121.77276,3.820,2010-01-01T00:16:49.375360Z,7.560,3.786,0.140,0.840,25,30,0.985,1
2,47.86208,-122.09903,17.799,2010-01-01T07:18:03.689209Z,5.118,4.807,0.195,0.741,10,18,0.784,2
3,47.96435,-122.91906,21.286,2010-01-01T08:51:56.371091Z,1.899,1.884,0.287,0.756,10,10,0.465,3
4,45.87262,-122.19180,9.822,2010-01-01T16:12:43.838660Z,2.842,2.838,0.229,0.850,20,19,0.657,4
...,...,...,...,...,...,...,...,...,...,...,...,...
63882,40.59439,-124.42438,19.741,2015-06-23T22:11:15.735288Z,30.487,10.400,0.331,0.654,9,14,1.015,63882
63883,40.54636,-127.10076,26.165,2015-06-23T22:45:51.899203Z,12.195,11.296,0.508,0.840,1,11,0.744,63883
63884,49.74167,-124.58578,5.274,2015-06-23T23:03:49.638010Z,21.070,2.023,0.461,0.801,7,6,0.894,63884
63885,40.64363,-125.36531,1.891,2015-06-23T23:12:21.788775Z,11.352,11.251,0.488,0.633,3,5,0.982,63885
63886,43.37085,-127.35251,5.915,2015-06-23T23:18:18.841147Z,4.265,4.239,0.370,0.694,4,5,0.447,63886

In [18]:
df_ver3.keys()

Index(['Latitude', ' Longitude', ' Depth (km)', ' Origin Time (UTC)',
       ' Uncertainity (km)', ' Horizontal Uncertainity (km)',
       ' Geometric Std. (km)', ' Detection Value', ' Num. P', ' Num. S',
       ' RMS Residual (s)', ' Event ID '],
      dtype='object')

##### Populate the columns of the updated file

In [19]:
df_updated[' Event ID '] = df_ver3[' Event ID ']
df_updated[' Depth (km)'] = df_updated[' Depth (m)']/1000
df_updated[' Detection Value'] = df_ver3[' Detection Value']
df_updated.head()

,Latitude,Longitude,Depth (m),sec_day,Event ID,Depth (km),Detection Value
0,47.13396,-122.09098,-60147.0,916.204,0,-60.1470,0.680
1,48.17742,-121.83289,-6163.0,1009.343,1,-6.1630,0.840
2,47.85353,-122.12435,-18296.0,26283.837,2,-18.2960,0.741
3,47.97665,-122.90617,-20910.0,31916.196,3,-20.9100,0.756
4,45.86019,-122.19002,-8403.5,58363.926,4,-8.4035,0.850

In [20]:
# Convert seconds to HH:MM:SS format
df_updated[' Origin Time (UTC)'] = pd.to_datetime(df_ver3[' Origin Time (UTC)']).dt.date.astype(str) + 'T' +pd.to_datetime(df_updated['sec_day'], unit='s').dt.strftime('%H:%M:%S.%fZ').astype(str)
df_updated.iloc[0:10]

,Latitude,Longitude,Depth (m),sec_day,Event ID,Depth (km),Detection Value,Origin Time (UTC)
0,47.13396,-122.09098,-60147.0,916.204,0,-60.1470,0.680,2010-01-01T00:15:16.204000Z
1,48.17742,-121.83289,-6163.0,1009.343,1,-6.1630,0.840,2010-01-01T00:16:49.343000Z
2,47.85353,-122.12435,-18296.0,26283.837,2,-18.2960,0.741,2010-01-01T07:18:03.837000Z
3,47.97665,-122.90617,-20910.0,31916.196,3,-20.9100,0.756,2010-01-01T08:51:56.196000Z
4,45.86019,-122.19002,-8403.5,58363.926,4,-8.4035,0.850,2010-01-01T16:12:43.926000Z
5,48.47310,-123.04700,-20635.5,65813.112,5,-20.6355,0.846,2010-01-01T18:16:53.111999Z
6,49.12783,-122.17863,-10840.5,70128.683,6,-10.8405,0.757,2010-01-01T19:28:48.683000Z
7,50.51896,-120.71528,-8914.5,74226.150,7,-8.9145,0.648,2010-01-01T20:37:06.150000Z
8,48.33845,-124.99159,1495.5,8113.994,8,1.4955,0.572,2010-01-02T02:15:13.994000Z
9,47.38612,-122.59334,-2877.5,8985.673,9,-2.8775,0.665,2010-01-02T02:29:45.673000Z

In [21]:
df_updated[' RMS Residual (s)'] = df_ver3[' RMS Residual (s)']
df_updated[' Num. P'] = df_ver3[' Num. P']
df_updated[' Num. S'] = df_ver3[' Num. S']
df_updated[' Depth (km)'] = df_updated[' Depth (km)'] * (-1)

In [22]:
df_updated = df_updated.drop(columns=[' Depth (m)', 'sec_day'])
df_updated

,Latitude,Longitude,Event ID,Depth (km),Detection Value,Origin Time (UTC),RMS Residual (s),Num. P,Num. S
0,47.13396,-122.09098,0,60.1470,0.680,2010-01-01T00:15:16.204000Z,1.081,2,5
1,48.17742,-121.83289,1,6.1630,0.840,2010-01-01T00:16:49.343000Z,0.985,25,30
2,47.85353,-122.12435,2,18.2960,0.741,2010-01-01T07:18:03.837000Z,0.784,10,18
3,47.97665,-122.90617,3,20.9100,0.756,2010-01-01T08:51:56.196000Z,0.465,10,10
4,45.86019,-122.19002,4,8.4035,0.850,2010-01-01T16:12:43.926000Z,0.657,20,19
...,...,...,...,...,...,...,...,...,...
63882,40.59877,-124.40572,63882,20.4825,0.654,2015-06-23T22:11:13.828000Z,1.015,9,14
63883,40.62611,-127.11445,63883,18.5140,0.840,2015-06-23T22:45:50.498000Z,0.744,1,11
63884,49.76714,-124.52950,63884,3.6850,0.801,2015-06-23T23:03:50.163000Z,0.894,7,6
63885,40.66547,-125.33902,63885,3.0525,0.633,2015-06-23T23:12:22.778000Z,0.982,3,5
63886,43.33308,-127.31240,63886,6.0615,0.694,2015-06-23T23:18:19.457000Z,0.447,4,5

In [23]:
df_updated.to_csv('/wd1/hbito_data/data/datasets_all_regions/Cascadia_updated_catalog_ver3.csv', index=False)